#define SPECIES_GENEMOD "genemod"
#define SPECIES_GENEMOD_PRIMITIVE "primitive_genemod"
#define SPECIES_RAMATAN "ramatan"
#define SPECIES_ANTHROMORPH "anthromorph"
#define SPECIES_INSECTOID "insectoid"
#define SPECIES_HEMOPHAGE "hemophage"
#define SPECIES_SLIMESTART "slimehybrid"

#define SPECIES_TIZIRIAN "tizirian"
#define SPECIES_TAJARAN "tajaran"
#define SPECIES_VULPKANIN "vulpkanin"
